const cfg=window.SMH_CONFIG||{};const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});let user=null,settings=null,jobs=[],filter='all';const $=id=>document.getElementById(id);let tt;function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(tt);tt=setTimeout(()=>$('toast').classList.remove('show'),2600)}function slug(){return 'smh-'+crypto.randomUUID().replace(/-/g,'').slice(0,12)}function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
document.querySelectorAll('.ap-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ap-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.ap-panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));if(b.dataset.tab==='jobs')loadJobs()});
document.querySelectorAll('.job-filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.job-filters button').forEach(x=>x.classList.toggle('active',x===b));renderJobs()});
async function boot(){const {data:{user:u}}=await sb.auth.getUser();if(!u){location.href='auth.html?next=auto-print.html';return}user=u;await loadSettings();await loadJobs();sb.channel('auto-print-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'print_jobs',filter:'user_id=eq.'+user.id},loadJobs).subscribe()}
async function loadSettings(){const {data,error}=await sb.from('auto_print_settings').select('*').eq('user_id',user.id).maybeSingle();if(error)return toast(error.message);settings=data||{user_id:user.id,shop_name:'SUNIL MULTI HUB',public_slug:slug(),agent_status:'offline',payment_provider:'not_connected',payment_mode:'manual',bw_id_price:5,color_id_price:10,bw_pdf_price:5,color_pdf_price:10,bw_a4_price:3,color_a4_price:10};fill()}
function fill(){$('shopName').value=settings.shop_name||'SUNIL MULTI HUB';$('bwId').value=settings.bw_id_price;$('colorId').value=settings.color_id_price;$('bwPdf').value=settings.bw_pdf_price;$('colorPdf').value=settings.color_pdf_price;$('bwA4').value=settings.bw_a4_price;$('colorA4').value=settings.color_a4_price;$('upiId').value=settings.merchant_upi_id||'';$('paymentMode').value=settings.payment_mode||'manual';$('printerName').value=settings.printer_name||'';const online=settings.agent_status==='online';$('statusText').textContent=online?'Agent Online':'Agent Offline';$('statusDot').style.background=online?'#10b981':'#ef4444';renderQr()}
async function save(patch){const row={...settings,...patch,user_id:user.id,updated_at:new Date().toISOString()};const {data,error}=await sb.from('auto_print_settings').upsert(row,{onConflict:'user_id'}).select().single();if(error)return toast(error.message);settings=data;const pub={user_id:user.id,public_slug:settings.public_slug,shop_name:settings.shop_name,merchant_upi_id:settings.merchant_upi_id||null,payment_mode:settings.payment_mode||'manual',active:Boolean(settings.merchant_upi_id&&(settings.payment_mode||'manual')==='manual'),bw_id_price:settings.bw_id_price,color_id_price:settings.color_id_price,bw_pdf_price:settings.bw_pdf_price,color_pdf_price:settings.color_pdf_price,bw_a4_price:settings.bw_a4_price,color_a4_price:settings.color_a4_price,updated_at:new Date().toISOString()};const {error:pe}=await sb.from('auto_print_public_shops').upsert(pub,{onConflict:'user_id'});if(pe)return toast(pe.message);fill();toast('Settings save हो गईं')}
$('settingsForm').onsubmit=e=>{e.preventDefault();save({shop_name:$('shopName').value.trim(),bw_id_price:+$('bwId').value,color_id_price:+$('colorId').value,bw_pdf_price:+$('bwPdf').value,color_pdf_price:+$('colorPdf').value,bw_a4_price:+$('bwA4').value,color_a4_price:+$('colorA4').value})};
$('saveUpi').onclick=()=>{const v=$('upiId').value.trim();if(v&&!/^[\w.-]{2,}@[\w.-]{2,}$/.test(v))return toast('सही UPI ID डालें');save({merchant_upi_id:v,payment_mode:$('paymentMode').value})};
$('verifyAgent').onclick=async()=>{const {data,error}=await sb.from('auto_print_agents').select('agent_name,status,printer_name,last_seen_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)return toast(error.message);if(!data)return toast('पहले Pair this PC से Device Token बनाएँ');toast(data.status==='online'?'Agent Online • '+(data.printer_name||data.agent_name):'Agent Offline • Last seen '+(data.last_seen_at?new Date(data.last_seen_at).toLocaleString('en-IN'):'never'))};
$('pairAgent').onclick=async()=>{const raw=new Uint8Array(32);crypto.getRandomValues(raw);const token=Array.from(raw,x=>x.toString(16).padStart(2,'0')).join('');const hashBytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));const hash=Array.from(new Uint8Array(hashBytes),x=>x.toString(16).padStart(2,'0')).join('');const {error}=await sb.from('auto_print_agents').insert({user_id:user.id,agent_name:'Shop PC',token_hash:hash,status:'offline',enabled:true});if(error)return toast(error.message);$('deviceToken').textContent=token;$('deviceTokenBox').classList.remove('hidden');toast('Device Token बन गया — अभी copy करें')};
$('copyDeviceToken').onclick=()=>navigator.clipboard.writeText($('deviceToken').textContent).then(()=>toast('Device Token copy हो गया'));
$('refreshJobs').onclick=loadJobs;
function renderQr(){const el=$('shopQr');el.innerHTML='';const url=location.origin+'/customer-print.html?shop='+encodeURIComponent(settings.public_slug);new QRCode(el,{text:url,width:190,height:190,colorDark:'#172033',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});const active=Boolean(settings.merchant_upi_id&&(settings.payment_mode||'manual')==='manual');el.classList.toggle('active',active);$('qrBadge').textContent=active?'ACTIVE':'INACTIVE';$('qrBadge').className='badge '+(active?'live':'warn');$('qrUrl').textContent=active?url:'Merchant UPI ID save करने के बाद QR active होगा।';$('copyQr').disabled=!active;$('printQr').disabled=!active;$('copyQr').onclick=()=>navigator.clipboard.writeText(url).then(()=>toast('QR link copy हो गया'));$('printQr').onclick=()=>{const w=window.open('','_blank');if(!w)return toast('Popup allow करें');w.document.write('<title>Shop Print QR</title><style>body{text-align:center;font-family:sans-serif;padding:30px}img{width:300px}h1{margin-bottom:4px}</style><h1>'+esc(settings.shop_name)+'</h1><p>Scan to Upload • Pay • Print</p>'+el.innerHTML);w.document.close();w.print()}}
async function loadJobs(){const {data,error}=await sb.from('print_jobs').select('id,file_path,original_name,service_type,color_mode,copies,page_count,amount,payment_status,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message);jobs=data||[];renderJobs()}
function renderJobs(){let list=jobs;if(filter!=='all')list=jobs.filter(x=>filter==='paid'?x.payment_status==='paid':x.status===filter);$('jobsList').innerHTML=list.length?list.map(x=>'<div class="job-row"><div><b>'+esc(x.original_name||x.service_type||'Print Job')+'</b><small>'+new Date(x.created_at).toLocaleString('en-IN')+' • '+esc(x.color_mode||'')+' • '+(x.page_count||1)+' page • '+(x.copies||1)+' copy</small></div><strong>'+money(x.amount)+'</strong><div><span class="job-state">'+esc(x.status||'pending')+'</span>'+(x.payment_status!=='paid'?'<button class="approve-job" data-id="'+x.id+'">Payment Received → Approve</button>':'')+'</div></div>').join(''):'<div class="empty-job">अभी कोई print job नहीं है।</div>';document.querySelectorAll('.approve-job').forEach(b=>b.onclick=()=>approveJob(b.dataset.id));const paid=jobs.filter(x=>x.payment_status==='paid');$('paidCount').textContent=paid.length+' paid jobs';$('todayRevenue').textContent=money(paid.filter(x=>new Date(x.created_at).toDateString()===new Date().toDateString()).reduce((s,x)=>s+Number(x.amount||0),0))}
async function approveJob(id){const job=jobs.find(x=>x.id===id);if(!job)return;const ok=confirm('क्या '+money(job.amount)+' payment आपके merchant account में मिल गया है? Approve करने पर job print queue में चली जाएगी।');if(!ok)return;const {error}=await sb.from('print_jobs').update({payment_status:'paid',status:'approved',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)return toast(error.message);toast('Payment approved — job print queue में है');loadJobs()}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}boot();