const cfg=window.SMH_CONFIG||{};const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});let user=null,settings=null,jobs=[],filter='all';const $=id=>document.getElementById(id);let tt;function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(tt);tt=setTimeout(()=>$('toast').classList.remove('show'),2600)}function slug(){return 'smh-'+crypto.randomUUID().replace(/-/g,'').slice(0,12)}function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
document.querySelectorAll('.ap-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ap-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.ap-panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));if(b.dataset.tab==='jobs')loadJobs()});
document.querySelectorAll('.job-filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.job-filters button').forEach(x=>x.classList.toggle('active',x===b));renderJobs()});
async function boot(){const {data:{user:u}}=await sb.auth.getUser();if(!u){location.href='auth.html?next=auto-print.html';return}user=u;await loadSettings();await loadJobs();sb.channel('auto-print-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'print_jobs',filter:'user_id=eq.'+user.id},loadJobs).subscribe()}
async function loadSettings(){const {data,error}=await sb.from('auto_print_settings').select('*').eq('user_id',user.id).maybeSingle();if(error)return toast(error.message);settings=data||{user_id:user.id,shop_name:'SUNIL MULTI HUB',public_slug:slug(),agent_status:'offline',payment_provider:'not_connected',bw_id_price:5,color_id_price:10,bw_pdf_price:5,color_pdf_price:10,bw_a4_price:3,color_a4_price:10};fill()}
function fill(){$('shopName').value=settings.shop_name||'SUNIL MULTI HUB';$('bwId').value=settings.bw_id_price;$('colorId').value=settings.color_id_price;$('bwPdf').value=settings.bw_pdf_price;$('colorPdf').value=settings.color_pdf_price;$('bwA4').value=settings.bw_a4_price;$('colorA4').value=settings.color_a4_price;$('upiId').value=settings.merchant_upi_id||'';$('printerName').value=settings.printer_name||'';const online=settings.agent_status==='online';$('statusText').textContent=online?'Agent Online':'Agent Offline';$('statusDot').style.background=online?'#10b981':'#ef4444';renderQr()}
async function save(patch){const row={...settings,...patch,user_id:user.id,updated_at:new Date().toISOString()};const {data,error}=await sb.from('auto_print_settings').upsert(row,{onConflict:'user_id'}).select().single();if(error)return toast(error.message);settings=data;fill();toast('Settings save हो गईं')}
$('settingsForm').onsubmit=e=>{e.preventDefault();save({shop_name:$('shopName').value.trim(),bw_id_price:+$('bwId').value,color_id_price:+$('colorId').value,bw_pdf_price:+$('bwPdf').value,color_pdf_price:+$('colorPdf').value,bw_a4_price:+$('bwA4').value,color_a4_price:+$('colorA4').value})};
$('saveUpi').onclick=()=>{const v=$('upiId').value.trim();if(v&&!/^[\w.-]{2,}@[\w.-]{2,}$/.test(v))return toast('सही UPI ID डालें');save({merchant_upi_id:v})};
$('verifyAgent').onclick=()=>toast('Windows Agent अभी install नहीं है');$('refreshJobs').onclick=loadJobs;
function renderQr(){const el=$('shopQr');el.innerHTML='';const url=location.origin+'/customer-print.html?shop='+encodeURIComponent(settings.public_slug);new QRCode(el,{text:url,width:190,height:190,colorDark:'#172033',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});$('qrUrl').textContent='Gateway और Agent connect होने के बाद QR active होगा।'}
async function loadJobs(){const {data,error}=await sb.from('print_jobs').select('id,original_name,service_type,color_mode,copies,page_count,amount,payment_status,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message);jobs=data||[];renderJobs()}
function renderJobs(){let list=jobs;if(filter!=='all')list=jobs.filter(j=>filter==='paid'?j.payment_status==='paid':j.status===filter);$('jobsList').innerHTML=list.length?list.map(j=>'<div class="job-row"><div><b>'+esc(j.original_name||j.service_type||'Print Job')+'</b><small>'+new Date(j.created_at).toLocaleString('en-IN')+' • '+esc(j.color_mode||j.print_mode||'')+' • '+(j.copies||1)+' copy</small></div><strong>'+money(j.amount)+'</strong><span class="job-state">'+esc(j.status||'pending')+'</span></div>').join(''):'<div class="empty-job">अभी कोई print job नहीं है।</div>';const paid=jobs.filter(j=>j.payment_status==='paid');$('paidCount').textContent=paid.length+' paid jobs';$('todayRevenue').textContent=money(paid.filter(j=>new Date(j.created_at).toDateString()===new Date().toDateString()).reduce((s,j)=>s+Number(j.amount||0),0))}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}boot();