(() => {
const cfg=window.SMH_CONFIG||{};const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey||cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);let rows=[],docsBy={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mask=v=>{const s=String(v||'');return s.length===12?`XXXX XXXX ${s.slice(-4)}`:s};
const label=s=>({new:'New',processing:'Processing',completed:'Completed',rejected:'Rejected'})[s]||s;
async function copy(t){try{await navigator.clipboard.writeText(t);alert('Copied');}catch(e){alert('Copy failed');}}
async function openDoc(id){const d=Object.values(docsBy).flat().find(x=>String(x.id)===String(id));if(!d)return;const {data,error}=await sb.storage.from('customer-intake-docs').createSignedUrl(d.storage_path,120);if(error)return alert(error.message);window.open(data.signedUrl,'_blank');}
function text(r){const extra=Object.entries(r.form_data||{}).map(([k,v])=>`${k}: ${v}`).join('\n');return [`Application ID: ${r.application_no||''}`,`Service: ${r.service_name||''}`,`Name: ${r.full_name||''}`,`Mobile: ${r.mobile||''}`,`DOB: ${r.dob||''}`,`Aadhaar: ${r.aadhaar||''}`,`PAN: ${r.pan||''}`,`Address: ${r.address||''}`,extra,`Note: ${r.notes||''}`].filter(Boolean).join('\n');}
function card(r){const docs=docsBy[r.id]||[];return `<article class="app-card"><div class="app-top"><div><span class="app-id">${esc(r.application_no)}</span><h3 style="margin:4px 0">${esc(r.full_name||'Customer')}</h3><div class="muted">${esc(r.service_name||'Service')} • ${esc(r.mobile||'')}</div></div><span class="status ${esc(r.status)}">${esc(label(r.status))}</span></div><div class="muted" style="margin-top:9px"><b>DOB:</b> ${esc(r.dob||'-')} &nbsp; <b>PAN:</b> ${esc(r.pan||'-')}<br><b>Aadhaar:</b> ${esc(mask(r.aadhaar)||'-')}<br><b>Address:</b> ${esc(r.address||'-')}</div>${docs.length?`<div style="margin-top:8px">${docs.map(d=>`<button class="doc-btn" data-doc="${esc(d.id)}">📎 ${esc(d.document_name||d.original_file_name||'Document')}</button>`).join('')}</div>`:''}<div class="app-grid"><label>Status<select class="st" data-id="${esc(r.id)}"><option value="new" ${r.status==='new'?'selected':''}>New</option><option value="processing" ${r.status==='processing'?'selected':''}>Processing</option><option value="completed" ${r.status==='completed'?'selected':''}>Completed</option><option value="rejected" ${r.status==='rejected'?'selected':''}>Rejected</option></select></label><label>Shop / Portal Application ID<input class="sid" data-id="${esc(r.id)}" value="${esc(r.shop_application_id||'')}" placeholder="Acknowledgement no."></label><label style="grid-column:1/-1">Owner Note<input class="note" data-id="${esc(r.id)}" value="${esc(r.owner_note||'')}" placeholder="Optional note"></label></div><div class="actions"><button class="btn secondary cp" data-id="${esc(r.id)}">Copy Details</button><button class="btn primary sv" data-id="${esc(r.id)}">Save Update</button></div></article>`;}
function bind(){document.querySelectorAll('.cp').forEach(b=>b.onclick=()=>{const r=rows.find(x=>String(x.id)===String(b.dataset.id));if(r)copy(text(r));});document.querySelectorAll('.sv').forEach(b=>b.onclick=()=>save(b.dataset.id));document.querySelectorAll('.doc-btn').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));}
function render(){ $('count').textContent=rows.length;$('rows').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No applications yet.</div>';bind();}
async function save(id){const r=rows.find(x=>String(x.id)===String(id));if(!r)return;const status=document.querySelector(`.st[data-id="${CSS.escape(String(id))}"]`)?.value||r.status;const shop=document.querySelector(`.sid[data-id="${CSS.escape(String(id))}"]`)?.value.trim()||null;const note=document.querySelector(`.note[data-id="${CSS.escape(String(id))}"]`)?.value.trim()||null;const patch={status,shop_application_id:shop,owner_note:note,completed_at:status==='completed'?new Date().toISOString():null,updated_at:new Date().toISOString()};const {error}=await sb.from('customer_intakes').update(patch).eq('id',id);if(error)return alert(error.message);Object.assign(r,patch);alert('Application updated');render();}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){location.replace('auth.html');return;}const link=`${location.origin}${location.pathname.replace(/client-form\.html.*$/,'')}self-form.html?center=${encodeURIComponent(session.user.id)}`;$('linkText').textContent=link;$('openForm').href=link;$('copyLink').onclick=()=>copy(link);await window.QRCode.toCanvas($('qr'),link,{width:200,margin:1});$('downloadQr').onclick=()=>{const a=document.createElement('a');a.download='Client-Form-QR.png';a.href=$('qr').toDataURL('image/png');a.click();};const {data,error}=await sb.from('customer_intakes').select('*').eq('owner_id',session.user.id).order('created_at',{ascending:false}).limit(200);if(error)throw error;rows=data||[];const ids=rows.map(r=>r.id);if(ids.length){const d=await sb.from('customer_intake_documents').select('*').in('intake_id',ids).order('created_at',{ascending:true});if(!d.error)(d.data||[]).forEach(x=>(docsBy[x.intake_id]??=[]).push(x));}render();}
boot().catch(e=>{$('rows').innerHTML=`<div class="empty">${esc(e.message||'Loading failed')}</div>`;});
})();