(() => {
const cfg=window.SMH_CONFIG||{};if(!window.supabase||!cfg.supabaseUrl)return;
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey||cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mask=v=>{const s=String(v||'');return s.length===12?`XXXX XXXX ${s.slice(-4)}`:s};
let rows=[],docsByIntake={};
async function copy(t){try{await navigator.clipboard.writeText(t);alert('Copied');}catch(e){alert('Copy failed');}}
function statusLabel(s){return({new:'New',processing:'Processing',completed:'Completed',rejected:'Rejected'})[s]||s;}
function allText(r){const extra=Object.entries(r.form_data||{}).map(([k,v])=>`${k}: ${v}`).join('\n');return[`Application ID: ${r.application_no||''}`,`Service: ${r.service_name||''}`,`Name: ${r.full_name||''}`,`Father/Husband: ${r.father_or_husband_name||''}`,`Mother: ${r.mother_name||''}`,`DOB: ${r.dob||''}`,`Gender: ${r.gender||''}`,`Mobile: ${r.mobile||''}`,`Email: ${r.email||''}`,`Aadhaar: ${r.aadhaar||''}`,`PAN: ${r.pan||''}`,`Address: ${r.address||''}`,extra,`Notes: ${r.notes||''}`].filter(Boolean).join('\n');}
function card(r,admin=false){const docs=docsByIntake[r.id]||[];return`<article class="smh-intake-card"><div class="smh-intake-top"><div><span class="smh-id">${esc(r.application_no)}</span><h3>${esc(r.full_name||'Customer')}</h3><div class="smh-muted">${esc(r.service_name||'Service')} • ${esc(r.mobile||'')}</div>${admin?`<div class="smh-muted">Client: ${esc(r.owner_name||r.owner_email||r.owner_id)}</div>`:''}</div><span class="smh-status ${esc(r.status)}">${esc(statusLabel(r.status))}</span></div><div class="smh-summary"><b>DOB:</b> ${esc(r.dob||'-')} &nbsp; <b>PAN:</b> ${esc(r.pan||'-')}<br><b>Aadhaar:</b> ${esc(mask(r.aadhaar)||'-')}<br><b>Address:</b> ${esc(r.address||'-')}</div>${docs.length?`<div class="smh-docs">${docs.map(d=>`<button type="button" class="smh-doc-btn" data-doc-id="${esc(d.id)}">📎 ${esc(d.document_name||d.original_file_name||'Document')}</button>`).join('')}</div>`:''}<div class="smh-actions"><button class="btn secondary smh-copy" data-id="${esc(r.id)}">Copy Details</button><select class="smh-status-select" data-id="${esc(r.id)}"><option value="new" ${r.status==='new'?'selected':''}>New</option><option value="processing" ${r.status==='processing'?'selected':''}>Processing</option><option value="completed" ${r.status==='completed'?'selected':''}>Completed</option><option value="rejected" ${r.status==='rejected'?'selected':''}>Rejected</option></select></div><div class="smh-grid"><label>Shop / Portal Application ID<input class="smh-shop-id" data-id="${esc(r.id)}" value="${esc(r.shop_application_id||'')}" placeholder="Application / acknowledgement no."></label><label>Owner Note<input class="smh-note" data-id="${esc(r.id)}" value="${esc(r.owner_note||'')}" placeholder="Optional note"></label></div><button class="btn primary smh-save" data-id="${esc(r.id)}" style="width:100%;margin-top:10px">Save Update</button></article>`;}
function css(){if(document.getElementById('smhCscCss'))return;const s=document.createElement('style');s.id='smhCscCss';s.textContent=`
.smh-top-tabs{position:sticky;top:0;z-index:1500;background:#fff;border-bottom:1px solid #e8edf5;box-shadow:0 6px 18px rgba(30,50,90,.05)}
.smh-top-tabs-inner{max-width:1180px;margin:auto;display:flex;align-items:stretch;overflow-x:auto;scrollbar-width:none;padding:0 10px}.smh-top-tabs-inner::-webkit-scrollbar{display:none}
.smh-top-tab{min-width:88px;flex:1;border:0;background:#fff;color:#52606f;text-decoration:none;padding:10px 12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;font:inherit;font-size:12px;font-weight:800;cursor:pointer;white-space:nowrap;border-bottom:3px solid transparent}
.smh-top-tab .ico{font-size:19px;line-height:1}.smh-top-tab.active,.smh-top-tab:hover{color:#1557d6;border-bottom-color:#1557d6;background:#f8faff}.smh-csc-badge{position:absolute;margin:-21px 0 0 28px;min-width:18px;height:18px;padding:0 4px;border-radius:999px;background:#ef4444;color:#fff;display:inline-grid;place-items:center;font-size:10px}
/* dashboard polish */
.customer-portal{background:#f7f9fd}.portal-header{background:#fff}.portal-hero{padding:18px 0 8px!important}.portal-banner{display:block!important;padding:20px!important;border-radius:24px!important;background:linear-gradient(135deg,#1262ed 0%,#3d4ce9 55%,#6f3fea 100%)!important;box-shadow:0 16px 34px rgba(40,71,210,.22)!important}.portal-banner-copy{max-width:none!important}.portal-banner-art{display:none!important}.portal-badge{display:none!important}.portal-banner h1{margin:0!important;color:#fff!important;font-size:26px!important;line-height:1.15!important}.portal-banner h1 span{display:none!important}.portal-banner-copy>p{margin:6px 0 0!important;color:rgba(255,255,255,.92)!important;font-size:14px!important}.portal-user{margin-top:8px!important;background:transparent!important;padding:0!important;border:0!important;color:#fff!important}.portal-user>span{display:none!important}.portal-user small{display:none!important}.portal-user strong{color:#fff!important;font-size:13px!important;font-weight:700!important}
.smh-hero-stats{margin-top:15px}.smh-hero-stats .portal-stat-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important}.smh-hero-stats .portal-stat-grid article{background:#fff!important;border:0!important;border-radius:14px!important;padding:12px!important;min-height:68px!important;box-shadow:none!important}.smh-hero-stats .portal-stat-grid article:nth-child(4){display:none!important}.smh-hero-stats .portal-stat-grid article:nth-child(5){display:flex!important}.smh-hero-stats .portal-stat-grid article span{font-size:21px!important}.smh-hero-stats .portal-stat-grid small{font-size:11px!important;color:#667085!important}.smh-hero-stats .portal-stat-grid strong{font-size:18px!important;color:#172033!important}
.smh-hero-wallet{margin-top:10px}.smh-hero-wallet>a{padding:12px 14px!important;border-radius:16px!important;background:rgba(255,255,255,.12)!important;box-shadow:none!important;border:1px solid rgba(255,255,255,.08)!important}.smh-hero-wallet a strong,.smh-hero-wallet a small{color:#fff!important}.portal-section-head{margin-bottom:12px!important}.portal-section-head h2{font-size:20px!important}.portal-service-grid{gap:12px!important}.portal-service-card{border-radius:16px!important;min-height:118px!important;padding:14px 10px!important;box-shadow:0 8px 22px rgba(25,45,90,.06)!important}.portal-service-icon{font-size:28px!important}.portal-service-card strong{font-size:13px!important;line-height:1.35!important}.portal-service-card small{font-size:11px!important}.portal-footer{margin-top:20px!important}
.smh-csc-modal{position:fixed;inset:0;background:rgba(8,18,38,.58);z-index:20000;display:none;align-items:flex-end;justify-content:center}.smh-csc-modal.show{display:flex}.smh-csc-sheet{width:min(820px,100%);max-height:94vh;overflow:auto;background:#f7f9fc;border-radius:26px 26px 0 0;padding:18px}.smh-sheet-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.smh-sheet-head h2{margin:3px 0}.smh-close{width:42px;height:42px;border:0;border-radius:50%;background:#fff;font-size:23px}.smh-qr-card{display:grid;grid-template-columns:200px 1fr;gap:18px;background:#fff;border:1px solid #e3e8f0;border-radius:20px;padding:16px;margin-top:14px}.smh-qr-card canvas{width:185px!important;height:185px!important;max-width:100%}.smh-link{font-size:12px;background:#f3f6fb;border-radius:12px;padding:10px;word-break:break-all}.smh-list{margin-top:14px}.smh-intake-card{background:#fff;border:1px solid #e4e9f1;border-radius:18px;padding:15px;margin:10px 0}.smh-intake-top{display:flex;justify-content:space-between;gap:12px}.smh-id{color:#1557d6;font-weight:900;font-size:12px}.smh-intake-card h3{margin:4px 0}.smh-muted{font-size:12px;color:#667085;line-height:1.5}.smh-status{padding:6px 9px;border-radius:999px;font-size:11px;font-weight:900;background:#eef4ff;color:#1557d6;height:max-content}.smh-status.completed{background:#ecfdf3;color:#067647}.smh-status.rejected{background:#fef3f2;color:#b42318}.smh-summary{font-size:13px;line-height:1.65;margin-top:10px}.smh-actions{display:flex;gap:8px;margin-top:12px}.smh-status-select{flex:1;padding:10px;border:1px solid #d8e0eb;border-radius:10px}.smh-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.smh-grid label{font-size:12px;font-weight:800}.smh-grid input{width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #d8e0eb;border-radius:10px}.smh-doc-btn{border:0;background:#f1f5fb;border-radius:9px;padding:7px 9px;margin:6px 5px 0 0;cursor:pointer}
@media(max-width:650px){.smh-top-tab{min-width:70px;padding:9px 6px;font-size:10.5px}.portal-hero{padding-top:12px!important}.portal-banner{padding:16px!important;border-radius:20px!important}.portal-banner h1{font-size:22px!important}.portal-banner-copy>p{font-size:12px!important}.smh-hero-stats .portal-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.smh-hero-stats .portal-stat-grid article{min-height:58px!important;padding:10px!important}.smh-hero-stats .portal-stat-grid article span{font-size:18px!important}.smh-hero-stats .portal-stat-grid strong{font-size:16px!important}.smh-hero-wallet>a{padding:10px 12px!important}.portal-service-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.portal-service-card{min-height:105px!important;padding:12px 8px!important}.smh-qr-card{grid-template-columns:1fr;text-align:center}.smh-grid{grid-template-columns:1fr}.smh-actions{flex-direction:column}}
`;document.head.appendChild(s);}
async function loadQrLib(){if(window.QRCode)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
async function openDoc(id){const d=Object.values(docsByIntake).flat().find(x=>String(x.id)===String(id));if(!d)return;const{data,error}=await sb.storage.from('customer-intake-docs').createSignedUrl(d.storage_path,120);if(error)return alert(error.message);window.open(data.signedUrl,'_blank');}
async function saveRow(id){const r=rows.find(x=>String(x.id)===String(id));if(!r)return;const sel=document.querySelector(`.smh-status-select[data-id="${CSS.escape(String(id))}"]`);const sid=document.querySelector(`.smh-shop-id[data-id="${CSS.escape(String(id))}"]`);const note=document.querySelector(`.smh-note[data-id="${CSS.escape(String(id))}"]`);const status=sel?.value||r.status;const patch={status,shop_application_id:sid?.value.trim()||null,owner_note:note?.value.trim()||null,completed_at:status==='completed'?new Date().toISOString():null,updated_at:new Date().toISOString()};const{error}=await sb.from('customer_intakes').update(patch).eq('id',id);if(error)return alert(error.message);Object.assign(r,patch);alert('Application updated');renderRows();}
function bind(){document.querySelectorAll('.smh-copy').forEach(b=>b.onclick=()=>{const r=rows.find(x=>String(x.id)===String(b.dataset.id));if(r)copy(allText(r));});document.querySelectorAll('.smh-save').forEach(b=>b.onclick=()=>saveRow(b.dataset.id));document.querySelectorAll('.smh-doc-btn').forEach(b=>b.onclick=()=>openDoc(b.dataset.docId));}
function renderRows(){const el=document.getElementById('smhCscRows');if(!el)return;el.innerHTML=rows.length?rows.map(r=>card(r,false)).join(''):'<div style="padding:22px;text-align:center;color:#667085">No customer forms yet.</div>';const badge=document.getElementById('smhCscBadge');if(badge){badge.textContent=rows.length;badge.style.display=rows.length?'inline-grid':'none';}bind();}
async function loadOwnerRows(uid){const{data,error}=await sb.from('customer_intakes').select('*').eq('owner_id',uid).order('created_at',{ascending:false}).limit(200);if(error)throw error;rows=data||[];const ids=rows.map(r=>r.id);docsByIntake={};if(ids.length){const d=await sb.from('customer_intake_documents').select('*').in('intake_id',ids).order('created_at',{ascending:true});if(!d.error)(d.data||[]).forEach(x=>(docsByIntake[x.intake_id]??=[]).push(x));}renderRows();}
function makeTopTabs(openClient){const old=document.getElementById('smhTopTabs');if(old)old.remove();const nav=document.createElement('nav');nav.id='smhTopTabs';nav.className='smh-top-tabs';nav.innerHTML=`<div class="smh-top-tabs-inner"><a class="smh-top-tab active" href="dashboard.html"><span class="ico">🏠</span><span>Dashboard</span></a><a class="smh-top-tab" href="#myOrders" onclick="document.getElementById('myOrders')?.scrollIntoView({behavior:'smooth'});return false"><span class="ico">📋</span><span>My Orders</span></a><button type="button" class="smh-top-tab" id="smhOpenCsc"><span class="ico">📝</span><span>Client Form</span><span class="smh-csc-badge" id="smhCscBadge" style="display:none">0</span></button><a class="smh-top-tab" href="wallet.html"><span class="ico">💰</span><span>Wallet</span></a><a class="smh-top-tab" href="tools.html"><span class="ico">🧰</span><span>Tools</span></a></div>`;const header=document.querySelector('.portal-header')||document.querySelector('header');if(header)header.insertAdjacentElement('afterend',nav);else document.body.insertAdjacentElement('afterbegin',nav);document.getElementById('smhOpenCsc').onclick=openClient;}
function polishDashboard(profile){const banner=document.querySelector('.portal-banner');if(!banner)return;const copyEl=banner.querySelector('.portal-banner-copy');if(copyEl){const name=profile?.full_name||'User';const h1=copyEl.querySelector('h1');if(h1)h1.innerHTML=`नमस्ते, ${esc(name)} 👋`;const p=copyEl.querySelector(':scope > p');if(p)p.textContent='SUNIL MULTI HUB में आपका स्वागत है।';const who=document.getElementById('who');if(who)who.textContent='आपका स्वागत है!';}
 const statSection=document.querySelector('.portal-stat-grid')?.closest('section');const statGrid=document.querySelector('.portal-stat-grid');if(statGrid&&!banner.querySelector('.smh-hero-stats')){const wrap=document.createElement('div');wrap.className='smh-hero-stats';wrap.appendChild(statGrid);banner.appendChild(wrap);if(statSection)statSection.style.display='none';}
 const wallet=document.getElementById('walletSection');const walletLink=wallet?.querySelector('a');if(walletLink&&!banner.querySelector('.smh-hero-wallet')){const wrap=document.createElement('div');wrap.className='smh-hero-wallet';wrap.appendChild(walletLink);banner.appendChild(wrap);wallet.style.display='none';}
}
async function dashboard(session,profile){css();polishDashboard(profile);const base=location.href.split('dashboard.html')[0];const link=`${base}self-form.html?center=${encodeURIComponent(session.user.id)}`;const modal=document.createElement('div');modal.className='smh-csc-modal';modal.id='smhCscModal';modal.innerHTML=`<div class="smh-csc-sheet"><div class="smh-sheet-head"><div><span style="color:#1557d6;font-weight:900">CLIENT FORM</span><h2>QR & Applications</h2><div class="smh-muted">QR scan या link से customer form भर सकता है।</div></div><button class="smh-close" id="smhCscClose">×</button></div><div class="smh-qr-card"><div><canvas id="smhQrCanvas"></canvas><div style="font-weight:800;margin-top:6px">Scan & Fill Form</div></div><div><div class="smh-link">${esc(link)}</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><a class="btn primary" href="${esc(link)}" target="_blank">Open Form</a><button class="btn secondary" id="smhCopyLink">Copy Link</button><button class="btn secondary" id="smhDownloadQr">Download QR</button></div></div></div><div class="smh-list"><h3>Client Applications</h3><div id="smhCscRows"><p>Loading...</p></div></div></div>`;document.body.appendChild(modal);const open=()=>modal.classList.add('show');makeTopTabs(open);document.getElementById('smhCscClose').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};document.getElementById('smhCopyLink').onclick=()=>copy(link);await loadQrLib();await window.QRCode.toCanvas(document.getElementById('smhQrCanvas'),link,{width:200,margin:1});document.getElementById('smhDownloadQr').onclick=()=>{const a=document.createElement('a');a.download='Client-Form-QR.png';a.href=document.getElementById('smhQrCanvas').toDataURL('image/png');a.click();};await loadOwnerRows(session.user.id);}
async function admin(){css();const main=document.querySelector('main .container')||document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.className='admin-card';sec.style.marginTop='18px';sec.innerHTML=`<div class="card-head"><div><span class="eyebrow">USER DATA</span><h2>👥 Client Form Applications</h2><p>सभी registered users के customer forms और Application IDs.</p></div></div><div id="smhCscRows"><p>Loading...</p></div>`;main.appendChild(sec);const{data,error}=await sb.from('customer_intakes_admin_view').select('*').order('created_at',{ascending:false}).limit(300);if(error){document.getElementById('smhCscRows').innerHTML=`<p>${esc(error.message)}</p>`;return;}rows=data||[];document.getElementById('smhCscRows').innerHTML=rows.length?rows.map(r=>card(r,true)).join(''):'<p>No customer forms yet.</p>';bind();}
async function boot(){const{data:{session}}=await sb.auth.getSession();if(!session)return;const{data:p}=await sb.from('profiles').select('role,full_name').eq('id',session.user.id).maybeSingle();if(location.pathname.endsWith('admin.html')&&p?.role==='admin')await admin();else if(location.pathname.endsWith('dashboard.html'))await dashboard(session,p);}
boot().catch(e=>console.error('Client form module:',e));
})();