(() => {
  const TARGET='वोटर ID सेवाएँ', PANEL_ID='smhVoterEciPanel';
  const SERVICE_ID='45ed1c1b-228e-4610-ac0a-3e397456656f', CHARGE=20;
  let sb=null,busy=false;
  const ECI={signup:'https://voters.eci.gov.in/signup',login:'https://voters.eci.gov.in/login',form6:'https://voters.eci.gov.in/form6',form8:'https://voters.eci.gov.in/form8',eepic:'https://voters.eci.gov.in/home/e-epic-download',search:'https://electoralsearch.eci.gov.in/',track:'https://voters.eci.gov.in/track-status',roll:'https://voters.eci.gov.in/download-eroll'};
  const SERVICES=[
    {icon:'🆕',title:'New Voter ID',desc:'पहली बार details भरें और ₹20 देकर ECI Sign-Up खोलें। Existing ECI account हो तो Login FREE है।',key:'new-voter',newVoter:true},
    {icon:'✏️',title:'Voter ID Correction / Shift',desc:'नाम, पता, फोटो या residence shift (Form 8).',url:ECI.form8,key:'form8-correction'},
    {icon:'📱',title:'Mobile Number Correction',desc:'EPIC ID और नया mobile number भरकर Form 8 खोलें.',url:ECI.form8,key:'form8-mobile',mobile:true},
    {icon:'🪪',title:'Replacement Voter ID',desc:'Lost/damaged EPIC replacement के लिए Form 8.',url:ECI.form8,key:'form8-replacement'},
    {icon:'⬇️',title:'Download e-EPIC',desc:'Digital Voter ID download करें.',url:ECI.eepic,key:'eepic'},
    {icon:'🔎',title:'Search Name in Voter List',desc:'नाम/EPIC से electoral roll में entry खोजें.',url:ECI.search,key:'search-roll'},
    {icon:'📍',title:'Track Application Status',desc:'Submitted voter application का status track करें.',url:ECI.track,key:'track'},
    {icon:'📄',title:'Download Electoral Roll',desc:'Official electoral roll PDF download करें.',url:ECI.roll,key:'eroll'}
  ];
  function client(){if(sb)return sb;const c=window.SMH_CONFIG||{};if(!window.supabase||!c.supabaseUrl||!(c.supabaseAnonKey||c.supabaseKey))throw Error('Portal configuration missing. Please refresh or contact support.');sb=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey||c.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
  function toast(m){const e=document.getElementById('toast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)}else alert(m)}
  function ref(k){return `voter:${k}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`}
  function openOfficial(url){const w=window.open(url,'_blank','noopener');if(!w)location.href=url}
  function paidKey(userId,key){return `smh-voter-paid:${userId}:${key}`}
  function setHandoff(message,type='info'){const e=document.querySelector(`#${PANEL_ID} .handoff`);if(!e)return;e.textContent=message;e.dataset.type=type;e.hidden=false}
  async function paidOpen(url,key,btn,meta={},options={}){if(busy)return;busy=true;const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Processing ₹20…'}const target=window.open('about:blank','_blank');try{const api=client();const {data:{session},error:sessionError}=await api.auth.getSession();if(sessionError)throw sessionError;if(!session)throw Error('Session expired. Please login again.');
      const marker=paidKey(session.user.id,key);
      if(options.oneTime&&localStorage.getItem(marker)==='paid'){if(target){target.opener=null;target.location.replace(url)}else location.href=url;setHandoff('इस account/browser से Sign-Up fee पहले paid है—ECI Sign-Up बिना दोबारा charge खोला गया।','success');toast('Already paid • No ₹20 deduction');return}
      const requestReference=options.oneTime?`voter:${key}:${session.user.id}`:ref(key);
      const {data,error}=await api.rpc('debit_wallet_for_service',{p_service_id:SERVICE_ID,p_request_reference:requestReference});if(error)throw error;if(!data?.success){if(target)target.close();if(data?.code==='INSUFFICIENT_BALANCE'){setHandoff('Wallet balance कम है। Recharge करके फिर कोशिश करें।','error');toast('Wallet balance कम है। ₹20 आवश्यक है।');return}throw Error(data?.message||'Payment failed')}
      try{sessionStorage.setItem(`smh-voter-${key}-draft`,JSON.stringify({...meta,savedAt:Date.now()}))}catch(_){}
      if(options.oneTime)try{localStorage.setItem(marker,'paid')}catch(_){}
      const copy=Object.entries(meta).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join('\n');let copied=false;if(copy)try{await navigator.clipboard.writeText(copy);copied=true}catch(_){}
      setHandoff(copied?'Details copied. ECI page पर paste करके OTP/captcha पूरा करें।':'ECI page खुल गया। Browser ने copy रोकी है—details यहाँ देखकर manually भरें।',copied?'success':'warning');
      if(target){target.opener=null;target.location.replace(url)}else location.href=url;toast(`₹20 deducted • ECI page opened${copied?' • Details copied':''}`);try{window.dispatchEvent(new CustomEvent('smh-wallet-updated',{detail:{balance:data.balance_after}}))}catch(_){}
    }catch(e){if(target)target.close();const m=/insufficient/i.test(String(e?.message))?'Wallet balance कम है। ₹20 आवश्यक है।':String(e?.message||'Service open failed');setHandoff(m,'error');toast(m)}finally{busy=false;if(btn){btn.disabled=false;btn.textContent=old}}}
  function showBox(cls){const p=ensurePanel();p.querySelectorAll('.ve-intake').forEach(x=>x.classList.remove('show'));const b=p.querySelector(cls);b?.classList.add('show');b?.scrollIntoView({behavior:'smooth',block:'center'})}
  function ensurePanel(){let p=document.getElementById(PANEL_ID);if(p)return p;const st=document.createElement('style');st.textContent=`#${PANEL_ID}{position:fixed;inset:0;z-index:32100;background:#f5f7fb;display:none;overflow:auto;font-family:Arial;color:#172033}#${PANEL_ID}.show{display:block}#${PANEL_ID} .shell{max-width:1120px;min-height:100%;margin:auto;background:#fff}#${PANEL_ID} header{position:sticky;top:0;z-index:5;background:linear-gradient(135deg,#ff7a00,#138808);color:#fff;padding:18px 56px 16px 18px}#${PANEL_ID} header h2{margin:0;font-size:25px}#${PANEL_ID} header p{margin:6px 0 0;font-size:13px}#${PANEL_ID} .close{position:absolute;right:14px;top:14px;width:38px;height:38px;border:0;border-radius:50%;background:#fff;font-size:24px}#${PANEL_ID} .info{margin:15px 16px;padding:13px;border-radius:14px;background:#eef5ff;border:1px solid #d5e3f8;font-size:13px}#${PANEL_ID} .grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:0 16px 18px}#${PANEL_ID} .card{border:1px solid #e1e7f0;border-radius:18px;padding:16px;display:flex;flex-direction:column;min-height:190px;box-shadow:0 8px 24px rgba(30,55,95,.06)}#${PANEL_ID} .card p{color:#667085;font-size:12.5px;line-height:1.5;flex:1}#${PANEL_ID} .price{font-weight:900;color:#138808;margin-top:8px}#${PANEL_ID} button.action,#${PANEL_ID} .primary{border:0;border-radius:10px;background:#1557d6;color:#fff;padding:11px;font-weight:900;cursor:pointer;width:100%;margin-top:10px}#${PANEL_ID} button:disabled{opacity:.58;cursor:not-allowed}#${PANEL_ID} .free{background:#138808!important}#${PANEL_ID} .secondary{background:#eef2f6!important;color:#344054!important}#${PANEL_ID} .handoff{margin:0 16px 14px;padding:11px;border-radius:10px;background:#eef5ff;font-size:12px;line-height:1.5}#${PANEL_ID} .handoff[data-type="error"]{background:#fff0f0;color:#9b1c1c}#${PANEL_ID} .handoff[data-type="warning"]{background:#fff8dd;color:#665200}#${PANEL_ID} .handoff[data-type="success"]{background:#eaf8ef;color:#176b35}#${PANEL_ID} .ve-intake{display:none;margin:0 16px 18px;padding:16px;border:1px solid #cfdcf0;border-radius:18px;background:#f8fbff}#${PANEL_ID} .ve-intake.show{display:block}#${PANEL_ID} .fields{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}#${PANEL_ID} label{font-size:12px;font-weight:800}#${PANEL_ID} input{width:100%;box-sizing:border-box;margin-top:5px;padding:11px;border:1px solid #ccd5e3;border-radius:9px}#${PANEL_ID} .note{margin-top:10px;padding:10px;background:#fff8dd;border:1px solid #edd98a;border-radius:10px;font-size:11px;line-height:1.5}#${PANEL_ID} .row{display:flex;gap:9px}#${PANEL_ID} .row button{flex:1} @media(max-width:820px){#${PANEL_ID} .grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){#${PANEL_ID} .grid{grid-template-columns:1fr;padding:0 10px 14px}#${PANEL_ID} .fields{grid-template-columns:1fr}#${PANEL_ID} .ve-intake{margin:0 10px 14px}}`;document.head.appendChild(st);
    p=document.createElement('section');p.id=PANEL_ID;p.innerHTML=`<div class="shell"><header><small>Election Commission of India • Citizen Services</small><h2>वोटर ID सेवाएँ</h2><p>₹20 paid services • Existing ECI account login FREE</p><button class="close">×</button></header><div class="info"><b>New Voter:</b> Sign-Up पर ₹20 सिर्फ पहली बार। Already registered ECI account के Login पर कोई charge नहीं।</div>
    <div class="handoff" role="status" aria-live="polite" hidden></div><div class="ve-intake newbox"><h3>🆕 New Voter Registration</h3><p>पहले basic details यहाँ तैयार रखें। ₹20 payment के बाद ECI Sign-Up खुलेगा। ECI captcha/OTP वहीं पूरा होगा।</p><div class="fields"><label>Full Name<input id="nvName" autocomplete="name"></label><label>Mobile Number<input id="nvMobile" type="tel" inputmode="numeric" maxlength="10"></label><label>Email (optional)<input id="nvEmail" type="email" autocomplete="email"></label><label>Date of Birth<input id="nvDob" type="date"></label></div><div class="note">Security restriction के कारण Multi Hub ECI के captcha या OTP को bypass नहीं करता और ECI page के fields को guaranteed auto-fill नहीं कर सकता। Details browser session में ready रहेंगी/copy की जाएँगी।</div><div class="row"><button class="primary nvPay">Pay ₹20 Once & Open ECI Sign-Up ↗</button><button class="primary free nvLogin">Already Registered? Login FREE ↗</button></div><button class="primary secondary cancelIntake">Cancel</button></div>
    <div class="ve-intake mobbox"><h3>📱 Mobile Number Correction</h3><div class="fields"><label>EPIC ID<input id="vmEpic" maxlength="20"></label><label>New Mobile Number<input id="vmMobile" type="tel" inputmode="numeric" maxlength="10"></label></div><div class="note">₹20 payment के बाद official Form 8 खुलेगा। ECI verification/OTP वहीं होगा।</div><button class="primary vmPay">Pay ₹20 & Open Form 8 ↗</button><button class="primary secondary cancelIntake">Cancel</button></div>
    <div class="grid">${SERVICES.map((s,i)=>`<article class="card"><div style="font-size:28px">${s.icon}</div><h3>${s.title}</h3><p>${s.desc}</p><div class="price">${s.newVoter?'₹20 Sign-Up • Login FREE':'₹20'}</div><button class="action" data-i="${i}">${s.newVoter?'Sign-Up / Login':s.mobile?'Enter Details':'Open Service ↗'}</button></article>`).join('')}</div></div>`;document.body.appendChild(p);
    const closePanel=()=>{p.classList.remove('show');p.querySelectorAll('.ve-intake').forEach(x=>x.classList.remove('show'));document.body.style.overflow=''};
    p.querySelector('.close').onclick=closePanel;
    p.querySelectorAll('.cancelIntake').forEach(b=>b.onclick=()=>b.closest('.ve-intake')?.classList.remove('show'));
    p.onclick=e=>{const b=e.target.closest('.action[data-i]');if(!b)return;const s=SERVICES[+b.dataset.i];if(!s)return;if(s.newVoter)return showBox('.newbox');if(s.mobile)return showBox('.mobbox');paidOpen(s.url,s.key,b)};
    p.querySelector('.nvLogin').onclick=()=>{setHandoff('Free ECI Login खोला जा रहा है—Multi Hub wallet से कोई charge नहीं होगा।','success');openOfficial(ECI.login)};
    p.querySelector('#nvMobile').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,10)};
    p.querySelector('#vmMobile').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,10)};
    p.querySelector('#vmEpic').oninput=e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,20)};
    p.querySelector('.nvPay').onclick=e=>{const name=p.querySelector('#nvName').value.trim(),mobile=p.querySelector('#nvMobile').value.replace(/\D/g,''),email=p.querySelector('#nvEmail').value.trim(),dob=p.querySelector('#nvDob').value;if(name.length<2)return toast('सही Full Name भरें');if(!/^[6-9]\d{9}$/.test(mobile))return toast('सही 10 digit mobile number भरें');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return toast('सही email भरें या खाली छोड़ें');if(!dob)return toast('Date of Birth चुनें');if(new Date(dob)>new Date())return toast('Date of Birth भविष्य की नहीं हो सकती');paidOpen(ECI.signup,'new-voter-signup',e.currentTarget,{Name:name,Mobile:mobile,Email:email,DOB:dob},{oneTime:true})};
    p.querySelector('.vmPay').onclick=e=>{const epic=p.querySelector('#vmEpic').value.toUpperCase().replace(/[^A-Z0-9]/g,''),mobile=p.querySelector('#vmMobile').value.replace(/\D/g,'');if(!/^[A-Z]{3}[0-9]{7}$/.test(epic))return toast('EPIC ID format सही भरें, जैसे ABC1234567');if(!/^[6-9]\d{9}$/.test(mobile))return toast('सही 10 digit mobile number भरें');paidOpen(ECI.form8,'form8-mobile',e.currentTarget,{EPIC:epic,'New Mobile':mobile})};return p}
  function openPanel(){ensurePanel().classList.add('show');document.body.style.overflow='hidden'}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){const p=document.getElementById(PANEL_ID);if(p?.classList.contains('show')){p.classList.remove('show');document.body.style.overflow=''}}});
  document.addEventListener('click',e=>{const c=e.target.closest('.portal-service-card');if(!c)return;const t=String(c.querySelector('strong')?.textContent||c.textContent||'').replace(/\s+/g,' ').trim();if(t!==TARGET)return;e.preventDefault();e.stopImmediatePropagation();openPanel()},true);window.openVoterEciServices=openPanel;
})();